### ISSUE TITLE
Public image not available

### ISSUE THREAD

**Issue by fr6nco** [bratislava/cert-manager-webhook-websupport#10]
Public docker image not available mentioned in the setup manual. Make image repo public so it can be used by anyone. 

Otherwise fully working DNS solver, tested by building the image manually and hosting on a private registry.

**Comment by vidriduch** [comment]
Hi, thank you for your feedback. Currently, we only publish the image to our _private_ repository for internal purposes. There is a plan in the future to have a _public_ repository, but currently, we don't want to maintain a new public organization repository just for one image.

So, for now closing it with **"won't fix"**.

With that said we provide a `Dockerfile` which you can build locally and use it and you can even publish it on your own.
